image: python:3.8

stages:
  - test

before_script:
  - python --version
  - pip install -r requirements.txt

test:
  stage: test
  allow_failure: true
  script:
    - python manage.py collectstatic
    - yes
    - python manage.py test

