image: python:3.8


stages:
  - test

before_script:
  - apk add build-base postgresql-dev
  - pip install -r requirements.txt


test:
  stage: test
  services:
    - postgres:12.2-alpine
  variables:
    POSTGRES_DB: activate
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: runner
    DB_HOST: postgres
    DB_NAME: activate
    DB_USER: runner
    DB_PASSWORD: runner
  script:
    - python manage.py test

