image: python:3.8

stages:
  - test

before_script:
  - python --version
  - pip install -r requirements.txt

test:
  stage: test
  allow_failure: true
  script:
    - python manage.py test

release-branch:
  stage: release
  image: registry.gitlab.com/gitlab-org/gitlab-releaser
  when: manual
  # We recommend the use of `except: tags` to prevent these pipelines
  # from running. See the notes section below for details.
  except:
    - tags
  script:
    - gitlab-releaser create --name release-branch-$CI_JOB_ID --description release-branch-$CI_COMMIT_REF_NAME-$CI_JOB_ID --tag-name job-$CI_JOB_ID --ref $CI_COMMIT_SHA
