# Generated by Django 3.0.3 on 2020-03-17 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5)),
                ('available', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(default=None)),
                ('room_type', models.CharField(choices=[('S', 'Single Occupancy'), ('D', 'Double Occupancy'), ('F', 'Firemannsrom')], default=None, max_length=1)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.AutoField(db_column='BookingID', primary_key=True, serialize=False)),
                ('cin_date', models.DateField(blank=True, db_column='CIN_Date', null=True, verbose_name='Check-In Date')),
                ('cout_date', models.DateField(blank=True, db_column='COUT_Date', null=True, verbose_name='Check-Out Date')),
                ('room_type', models.CharField(choices=[('S', 'Single Occupancy'), ('D', 'Double Occupancy'), ('F', 'Firemannsrom')], default=None, max_length=1)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(db_column='Room', default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Room')),
            ],
            options={
                'db_table': 'Booking',
                'managed': True,
            },
        ),
    ]
