# Generated by Django 3.0.3 on 2020-02-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(db_column='Room', default=12, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Room'),
        ),
    ]
