# Generated by Django 3.0.3 on 2020-03-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(db_column='Room', default=20, on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
    ]
