# Generated by Django 3.0.3 on 2020-03-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200303_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(db_column='Room', default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Room'),
        ),
    ]
